// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkaUPilOi9A72Wu-BLr_C3bCRlov8hXiM',
    appId: '1:1070166841443:web:3778cb61059fea59508056',
    messagingSenderId: '1070166841443',
    projectId: 'tourism-app-4d93f',
    authDomain: 'tourism-app-4d93f.firebaseapp.com',
    storageBucket: 'tourism-app-4d93f.appspot.com',
    measurementId: 'G-2L0XKE78B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlowF6Q4VPOCSbiUKO2oFbDJGHdwf1UNc',
    appId: '1:1070166841443:android:dbf57383d3a4152e508056',
    messagingSenderId: '1070166841443',
    projectId: 'tourism-app-4d93f',
    storageBucket: 'tourism-app-4d93f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3h9GYxlQgkq-HVv4RJ5lbs_6B_XBAyu0',
    appId: '1:1070166841443:ios:4f9d65dd5132d80a508056',
    messagingSenderId: '1070166841443',
    projectId: 'tourism-app-4d93f',
    storageBucket: 'tourism-app-4d93f.appspot.com',
    iosBundleId: 'com.example.waTourismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkaUPilOi9A72Wu-BLr_C3bCRlov8hXiM',
    appId: '1:1070166841443:web:93ec53796d718853508056',
    messagingSenderId: '1070166841443',
    projectId: 'tourism-app-4d93f',
    authDomain: 'tourism-app-4d93f.firebaseapp.com',
    storageBucket: 'tourism-app-4d93f.appspot.com',
    measurementId: 'G-DWP91ZVVEW',
  );
}
